### ISSUE TITLE
oauth2 not working with Python 3.4

### ISSUE THREAD

**Issue by tovikramin** [wndhydrnt/python-oauth2#23]
Hi,
i am getting this error on running
python twitterstream_vik.py > output.txt

Traceback (most recent call last):
  File "twitterstream_vik.py", line 1, in <module>
    import oauth2 as oauth
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1916, in _get_spec
  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location
  File "C:\Python34\lib\site-packages\oauth2-1.5.211-py3.4.egg\oauth2__init__.p
y", line 105
    except UnicodeDecodeError, le:
                             ^
SyntaxError: invalid syntax

Regards,
vik

**Comment by wndhydrnt** [comment]
This project is not maintained anymore. Closing this ticket before archiving the project on GitHub.
